# Generated by Django 5.0.7 on 2024-07-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_staff_email_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
